kind: Deployment
apiVersion: apps/v1
metadata:
  name: van-blog
  labels:
    app: van-blog
spec:
  selector:
    matchLabels:
      app: van-blog
  template:
    metadata:
      labels:
        app: van-blog
    spec:
      volumes:
        - name: host-time
          hostPath:
            path: /etc/localtime
            type: ''
        - name: static
          hostPath:
            path: /var/k8s/van-blog/static
            type: ''
        - name: log
          hostPath:
            path: /var/k8s/van-blog/log
            type: ''
      containers:
        - name: van-blog
          image: 'mereith/van-blog:latest'
          ports:
            - name: http-80
              containerPort: 80
              protocol: TCP
          env:
            - name: VAN_BLOG_DATABASE_URL
              value: 'mongodb://some:some@mongodb:27017/vanBlog?authSource=admin'
            - name: EMAIL
              value: >-
                vanblog@mereith.com
          resources:
            requests:
              memory: '300Mi'
              cpu: '250m'
            limits:
              memory: '800Mi'
              cpu: '800m'
          volumeMounts:
            - name: host-time
              readOnly: true
              mountPath: /etc/localtime
            - name: static
              mountPath: /app/static
            - name: log
              mountPath: /var/log
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: van-blog
spec:
  selector:
    app: van-blog
  ports:
    - name: http-80
      protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: van-ingress
  annotations:
    traefik.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: nasa1024.q-wifi.com
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: van-blog
                port:
                  number: 80