apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
        listen 80;
        location /image/ {
            root /usr/share/nginx/html;
            try_files $uri $uri/ =404;
        }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-file-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: static-file-server
  template:
    metadata:
      labels:
        app: static-file-server
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: nginx-config
        - name: static-files
          hostPath:
            path: /home/ubuntu/model/record
            type: Directory
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "0.3"
            memory: "100Mi"
          requests:
            cpu: "0.1"
        volumeMounts:
        - name: config-volume
          mountPath: /etc/nginx/conf.d
        - name: static-files
          mountPath: /usr/share/nginx/html/image
---
apiVersion: v1
kind: Service
metadata:
  name: static-file-server
spec:
  selector:
    app: static-file-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: airdropsharing-route
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix(`/image/`)
      kind: Rule
      services:
      - name: static-file-server
        port: 80

